version: '3'
services:
  app:
    image: nestjs/cli
    ports:
      - 3030:3000
    volumes: 
      -  ./:/workspace/
    links:
      - db
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    ports:
      - 13306:3306
  